const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');let errors=[],results=[];
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\//,'')||'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf8':f.endsWith('.js')?'application/javascript':'application/octet-stream');let s=fs.readFileSync(f);if(f.endsWith('index.html'))s=s.toString().replace('\n})();\n</script>','\nwindow.__g={pages:()=>PAGES,fillPage,switchEdition,setLabel,selectReaderPane};\n})();\n</script>');res.end(s)});
const profiles=[['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']];
async function run(browser,cfg){let [name,w,h,device]=cfg,c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});try{await c.addInitScript(({device})=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154','hk');localStorage.setItem('hk-device-layout-v146',device);Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5})},{device});let p=await c.newPage();p.on('pageerror',e=>errors.push(name+':'+e.message));await p.route('**/sw.js',r=>r.fulfill({status:404,body:''}));await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.waitForSelector('.txt');await p.evaluate(()=>document.fonts.ready);
for(let [ed,label] of [['hk','gz'],['zang','gz'],['zang','zj']]){await p.evaluate(async({ed,label})=>{await __g.switchEdition(ed);__g.setLabel(label);__g.selectReaderPane('chart',false)},{ed,label});await p.evaluate(()=>document.fonts.ready);let total=await p.evaluate(()=>__g.pages().length);let r={name,ed,label,pages:total,overflow:[],overlap:[],crossings:[],lost:[],fitted:[],page998:null};
for(let start=0;start<total;start+=35){let rows=await p.evaluate(({start,total})=>{let out=[],pz=document.getElementById('pzoom'),host=document.createElement('div');host.className='ksheet phone-page';host.style.cssText='display:block!important;flex:none';pz.prepend(host);
for(let i=start;i<Math.min(start+35,total);i++){let original=[...__g.pages()[i].matchAll(/data-id=["']?(-?\d+)/g)].map(m=>m[1]);__g.fillPage(host,i+2);let pg=host.querySelector('.page'),pr=pg.getBoundingClientRect(),scale=pr.width/210;if(!scale)throw Error('invisible paper');let actual=new Set([...pg.querySelectorAll('[data-id]')].map(e=>e.dataset.id)),lost=original.filter(id=>!actual.has(id)),bad=[],rects=[],bounds={l:Infinity,t:Infinity,r:-Infinity,b:-Infinity};function add(br,id,tree){if(!br.width&&!br.height)return;if(br.left<pr.left-.8||br.right>pr.right+.8||br.top<pr.top-.8||br.bottom>pr.bottom+.8)bad.push(id);if(tree){bounds.l=Math.min(bounds.l,(br.left-pr.left)/scale);bounds.t=Math.min(bounds.t,(br.top-pr.top)/scale);bounds.r=Math.max(bounds.r,(br.right-pr.left)/scale);bounds.b=Math.max(bounds.b,(br.bottom-pr.top)/scale);}}
for(let e of pg.querySelectorAll('.nd,.head,.pno,.ref')){let range=document.createRange();range.selectNodeContents(e);let br=range.getBoundingClientRect();add(e.getBoundingClientRect(),e.dataset.id||'header',e.classList.contains('nd'));add(br,e.dataset.id||'header',e.classList.contains('nd'));if(e.classList.contains('nd'))rects.push({id:e.dataset.id||e.dataset.go,x:(br.left-pr.left)/scale,y:(br.top-pr.top)/scale,w:br.width/scale,h:br.height/scale});}
let lines=[...pg.querySelectorAll('svg.ln line')].map(e=>{let b=e.getBoundingClientRect();add(b,'line',true);return{x0:(b.left-pr.left)/scale,x1:(b.right-pr.left)/scale,y0:(b.top-pr.top)/scale,y1:(b.bottom-pr.top)/scale}}),overlap=[],crossings=[];
for(let a=0;a<rects.length;a++)for(let b=a+1;b<rects.length;b++){let r=rects[a],q=rects[b];if(r.id===q.id)continue;let dx=Math.min(r.x+r.w,q.x+q.w)-Math.max(r.x,q.x),dy=Math.min(r.y+r.h,q.y+q.h)-Math.max(r.y,q.y);if(dx>.7&&dy>1)overlap.push([r.id,q.id]);}
for(let l of lines)for(let r of rects){let dx=Math.min(r.x+r.w,l.x1)-Math.max(r.x,l.x0),dy=Math.min(r.y+r.h,l.y1)-Math.max(r.y,l.y0);if((l.x1-l.x0<.01&&l.x0>r.x+.6&&l.x0<r.x+r.w-.6&&dy>1.5)||(l.y1-l.y0<.01&&l.y0>r.y+1&&l.y0<r.y+r.h-1&&dx>1))crossings.push(r.id);}
out.push({p:i+2,bad,overlap,crossings,lost,fitted:pg.dataset.boundsFit||null,bounds});}
host.remove();return out},{start,total});for(let x of rows){if(x.bad.length)r.overflow.push(x);if(x.overlap.length)r.overlap.push(x);if(x.crossings.length)r.crossings.push(x);if(x.lost.length)r.lost.push(x);if(x.fitted)r.fitted.push({p:x.p,scale:x.fitted});if(x.p===998)r.page998=x;}}
results.push(r);console.log(name,ed,label,'pages',total,'issues',r.overflow.length,r.overlap.length,r.crossings.length,r.lost.length);fs.writeFileSync(path.join(root,'tools/devices178-results.json'),JSON.stringify({results,errors},null,2));assert.equal(r.overflow.length+r.overlap.length+r.crossings.length+r.lost.length,0);}
}finally{await c.close();}}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let b=await chromium.launch({executablePath:'/tmp/chrome176/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-dev-shm-usage']});try{let queue=[...profiles];await Promise.all([0,1].map(async()=>{while(queue.length)await run(b,queue.shift())}));assert.deepEqual(errors,[])}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
