const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),errors=[],results=[];
const server=http.createServer((req,res)=>{let file=path.join(root,req.url.split('?')[0].replace(/^\//,'')||'index.html');if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':'application/octet-stream');if(file.endsWith('index.html')){let s=fs.readFileSync(file,'utf8').replace('\n})();\n</script>','\nwindow.__r={state:()=>({S,screen:ReaderUI.screen,LABEL,EDITION,zoom:Z.p,pending:pendingPanel}),N:()=>N,focusNode,openText,renderRail,panelPage,setLabel,goJuan,chartAnchor,selectReaderPane,saveReadingPosition,ranges:()=>JRANGE,firsts:()=>JFIRSTPAGE,viewportBox,overlayBounds};\n})();\n</script>');res.end(s);}else fs.createReadStream(file).pipe(res);});
let browser;
(async()=>{await new Promise(r=>server.listen(8784,'127.0.0.1',r));browser=await chromium.launch({executablePath:'/tmp/headless161/chrome-linux/headless_shell',args:['--no-sandbox','--disable-dev-shm-usage']});
for(let ed of ['hk','zang']){const c=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)'});await c.addInitScript(ed=>{try{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154',ed)}catch(e){}},ed);await c.route('**/sw.js',r=>r.fulfill({status:404}));await c.route('https://deerpark.app/**',r=>r.fulfill({contentType:'text/html',body:'<p>測試詞條</p>'}));const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8784/#j67');await p.waitForSelector('#volume-67');
for(let j=1;j<=100;j++){await p.evaluate(j=>__r.goJuan(j),j);await p.waitForTimeout(75);let st=await p.evaluate(()=>__r.state());assert.equal(st.S.juan,j);assert.equal(st.S.railJuan,j);assert.equal(await p.locator('.reading-volume').count(),1);let r=await p.evaluate(j=>__r.firsts()[j],j);assert.equal(st.S.ppage,r,`chart wrong volume ${ed} ${j}`);let ids=await p.locator('.rol a').evaluateAll(es=>es.slice(0,5).map(e=>+e.dataset.n));for(let i of ids){await p.evaluate(({i,j})=>__r.focusNode(i,'rail',null,j),{i,j});assert.equal((await p.evaluate(()=>__r.state())).S.juan,j,`inherited heading ${ed} ${j}/${i}`);}}
console.log('PASS',ed,'all 100 volumes and first 5 headings');for(let j of [2,18,19,32,41,73,76,77,78]){await p.evaluate(j=>__r.goJuan(j),j);await p.locator('[data-screen=catalog]').click();let carry=p.locator('.rol a[data-carry]');if(await carry.count()){await carry.first().tap();await p.waitForTimeout(350);assert.equal((await p.evaluate(()=>__r.state())).S.juan,j,'carried heading changed volume');await p.locator('[data-screen=chart]').click();await p.waitForTimeout(100);assert.equal((await p.evaluate(()=>__r.state())).S.juan,j)}await p.locator('[data-screen=read]').click()}
await p.evaluate(()=>__r.goJuan(67));await p.waitForTimeout(1900);await p.evaluate(()=>scrollTo(0,Math.min(800,document.scrollingElement.scrollHeight/3)));await p.waitForTimeout(100);const session=await c.newCDPSession(p);
async function pull(ys){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:210,y:ys[0],id:1}]});for(const y of ys.slice(1)){await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y,id:1}]});await p.waitForTimeout(40)}await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(250)}
await pull([560,530,480,410]);assert.equal((await p.evaluate(()=>__r.state())).S.juan,67,'mid-volume changed');
await p.evaluate(()=>scrollTo(0,document.scrollingElement.scrollHeight));await p.waitForTimeout(130);await pull([560,540,510]);assert.equal((await p.evaluate(()=>__r.state())).S.juan,67,'short boundary changed');
await p.evaluate(()=>scrollTo(0,document.scrollingElement.scrollHeight));await p.waitForTimeout(130);await pull([560,540,500,450,400]);assert.equal((await p.evaluate(()=>__r.state())).S.juan,68,'end pull did not change');await p.waitForTimeout(1000);assert.equal(await p.locator('.reading-volume').count(),1);
await p.evaluate(()=>__r.goJuan(100));await p.waitForTimeout(1300);await p.evaluate(()=>scrollTo(0,document.scrollingElement.scrollHeight));await p.waitForTimeout(100);await pull([560,530,480,400]);assert.equal((await p.evaluate(()=>__r.state())).S.juan,100,'beyond last volume');
await p.evaluate(()=>__r.goJuan(67));await p.waitForTimeout(1800);await p.evaluate(()=>{const node=document.querySelector('#article .txt p')?.firstChild;if(!node)return;let r=document.createRange();r.selectNodeContents(node);getSelection().removeAllRanges();getSelection().addRange(r)});await p.waitForTimeout(800);await p.locator('.dict-chip').click();await p.waitForTimeout(300);let bounds=await p.evaluate(()=>{const r=document.getElementById('termPreview').getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,b:__r.overlayBounds()}});assert(bounds.top>=bounds.b.top-1&&bounds.bottom<=bounds.b.bottom+1,'dictionary overflow');assert(Math.abs(bounds.bottom-bounds.b.bottom)<3,'dictionary not bottom');await p.locator('#termPreviewClose').click();await p.waitForFunction(()=>document.getElementById('termPreview').hidden,{}, {timeout:3000});assert(await p.locator('#termPreview').evaluate(e=>e.hidden));console.log('PASS',ed,'volume boundary and bottom dictionary');await c.close();}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'edges161-results.json'),JSON.stringify({all100Volumes:true,firstFiveHeadingsBothEditions:true,volumeBoundary:true,bottomDictionary:true,errors},null,2));await browser.close();server.close();})().catch(async e=>{console.error(e.stack);if(browser)await browser.close();server.close();process.exitCode=1});
