const fs=require('fs'),http=require('http'),path=require('path'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');let errors=[];
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\//,'')||'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf8':f.endsWith('.js')?'application/javascript':'application/octet-stream');let s=fs.readFileSync(f);if(f.endsWith('index.html'))s=s.toString().replace('\n})();\n</script>','\nwindow.__g={pages:()=>PAGES,fillPage,switchEdition,setLabel,fitChartBounds};\n})();\n</script>');res.end(s)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let b=await chromium.launch({executablePath:'/tmp/chrome176/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-dev-shm-usage']});try{let p=await b.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154','hk')});await p.route('**/sw.js',r=>r.fulfill({status:404,body:''}));await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.waitForSelector('.txt');await p.evaluate(()=>document.fonts.ready);let results=[];
for(let [ed,label] of [['hk','gz'],['zang','gz'],['zang','zj']]){await p.evaluate(async({ed,label})=>{await __g.switchEdition(ed);__g.setLabel(label)}, {ed,label});await p.evaluate(()=>document.fonts.ready);let total=await p.evaluate(()=>__g.pages().length),all=[],summary={ed,label,pages:total};
for(let start=0;start<total;start+=40){let rows=await p.evaluate(({start,total})=>{let out=[];let host=document.createElement('div');host.className='ksheet';host.style.cssText='position:fixed;left:0;top:0;width:793.7px;height:1122.5px;z-index:9999;--ks:1';document.body.appendChild(host);
for(let i=start;i<Math.min(start+40,total);i++){__g.fillPage(host,i+2);let pg=host.querySelector('.page'),pr=pg.getBoundingClientRect(),scale=pr.width/210,nds=[...pg.querySelectorAll('.nd')],bad=[],headerBad=[];let bounds={l:Infinity,t:Infinity,r:-Infinity,b:-Infinity};
function record(r,id,type){let x=(r.left-pr.left)/scale,y=(r.top-pr.top)/scale,rr=(r.right-pr.left)/scale,bb=(r.bottom-pr.top)/scale;if(!r.width&&!r.height)return;bounds.l=Math.min(bounds.l,x);bounds.t=Math.min(bounds.t,y);bounds.r=Math.max(bounds.r,rr);bounds.b=Math.max(bounds.b,bb);if(x<-.05||y<-.05||rr>210.05||bb>297.05)bad.push({id,type,x,y,r:rr,b:bb})}
for(let el of nds){record(el.getBoundingClientRect(),el.dataset.id||el.dataset.go,'box');let rg=document.createRange();rg.selectNodeContents(el);record(rg.getBoundingClientRect(),el.dataset.id||el.dataset.go,'text')}
for(let ln of pg.querySelectorAll('svg.ln line'))record(ln.getBoundingClientRect(),'line','line');
for(let el of pg.querySelectorAll('.head,.pno')){let rg=document.createRange();rg.selectNodeContents(el);let r=rg.getBoundingClientRect();if(r.left<pr.left-.7||r.right>pr.right+.7||r.top<pr.top-.7||r.bottom>pr.bottom+.7)headerBad.push({text:el.textContent.slice(0,60),x:(r.left-pr.left)/scale,y:(r.top-pr.top)/scale,r:(r.right-pr.left)/scale,b:(r.bottom-pr.top)/scale})}let rects=nds.map(e=>{let r=document.createRange();r.selectNodeContents(e);let b=r.getBoundingClientRect();return {id:e.dataset.id||e.dataset.go,x:(b.left-pr.left)/scale,y:(b.top-pr.top)/scale,w:b.width/scale,h:b.height/scale}}),overlap=[];
for(let a=0;a<rects.length;a++)for(let b=a+1;b<rects.length;b++){let r=rects[a],q=rects[b];if(r.id===q.id)continue;let dx=Math.min(r.x+r.w,q.x+q.w)-Math.max(r.x,q.x),dy=Math.min(r.y+r.h,q.y+q.h)-Math.max(r.y,q.y);if(dx>.7&&dy>1)overlap.push({a:r.id,b:q.id,dx,dy})}
let crossings=[];for(let ln of pg.querySelectorAll('svg.ln line')){let lr=ln.getBoundingClientRect(),x0=(lr.left-pr.left)/scale,x1=(lr.right-pr.left)/scale,y0=(lr.top-pr.top)/scale,y1=(lr.bottom-pr.top)/scale;for(let r of rects){let dx=Math.min(r.x+r.w,x1)-Math.max(r.x,x0),dy=Math.min(r.y+r.h,y1)-Math.max(r.y,y0);if((x1-x0<.01&&x0>r.x+.6&&x0<r.x+r.w-.6&&dy>1.5)||(y1-y0<.01&&y0>r.y+1&&y0<r.y+r.h-1&&dx>1))crossings.push({id:r.id,x0,x1,y0,y1,r});}}out.push({p:i+2,bounds,bad,headerBad,overlap,crossings,fitted:pg.dataset.boundsFit||null});}
host.remove();return out},{start,total});all.push(...rows)}
summary.headerOverflow=all.filter(x=>x.headerBad.length);summary.fitted=all.filter(x=>x.fitted);summary.overflow=all.filter(x=>x.bad.length);summary.overlap=all.filter(x=>x.overlap.length);summary.edge=all.filter(x=>x.bounds.l<4||x.bounds.r>206||x.bounds.t<4||x.bounds.b>290);summary.crossings=all.filter(x=>x.crossings.length);summary.page998=all.find(x=>x.p===998);results.push(summary);console.log(ed,label,'headerOverflow',summary.headerOverflow.length,'fitted',summary.fitted.length,'overflow',summary.overflow.length,'overlaps',summary.overlap.length,'edge',summary.edge.length,'crossings',summary.crossings.length,'998',JSON.stringify(summary.page998));fs.writeFileSync(path.join(root,'tools/geometry178-results.json'),JSON.stringify({results,errors},null,2));}
}finally{await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
