const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');let errors=[],results=[];
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/yogacara\//,'')||'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf8':f.endsWith('.js')?'application/javascript':'application/octet-stream');let s=fs.readFileSync(f);if(f.endsWith('index.html'))s=s.toString().replace('\n})();','\nwindow.__r={S,goJuan,selectReaderPane,showSettingsPage,openMenu,setLabel,focusNode,spy,railFocus,applyChartTitleColor,panelPage,fitChartBounds,fillPage,applyZoom,Z,get N(){return N}};\n})();');if(f.endsWith('index.html'))s=s.toString().replace("$('termPreviewClose').onclick=hidePreview;","window.__dictPreview=showPreview;$('termPreviewClose').onclick=hidePreview;");res.end(s);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser=await chromium.launch({executablePath:'/tmp/chrome176/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});try{
let profiles=[['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']];async function check([name,w,h,device,edition]){
if(process.env.DESKTOP_ONLY&&device!=='mac')return;let c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});await c.addInitScript(({edition,device})=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154',edition);localStorage.setItem('hk-device-layout-v146',device);Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5});},{edition,device});let p=await c.newPage();p.on('pageerror',e=>{errors.push(name+':'+e.message);console.error('PAGE',e.message)});await p.route('**/sw.js',r=>r.fulfill({status:404,body:''}));await p.goto(`http://127.0.0.1:${server.address().port}/yogacara/`);await p.waitForSelector('.txt');await p.waitForTimeout(900);
await p.route('https://deerpark.app/api/v1/dict/lookup/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({word:'瑜伽',data:[{dict:'測試辭典',expl:'<p>這是詞條內容，用來驗證字體、間距與倍率。</p><script>throw 1</script>'}]})}));
assert.deepEqual(await p.evaluate(()=>({r:__r.Z.r,m:__r.Z.m})),device==='mac'?{r:1.2,m:1.2}:{r:1,m:1});
await p.evaluate(()=>{let n=document.querySelector('#article .txt p').firstChild;let r=document.createRange();r.selectNodeContents(n);window.__dictPreview('瑜伽',r)});
await p.waitForSelector('.dict-local p');await p.waitForTimeout(300);
let dict=await p.locator('#termPreview').evaluate(el=>{let r=el.getBoundingClientRect(),d=el.querySelector('.dict-local');return{x:r.x,y:r.y,w:r.width,h:r.height,font:parseFloat(getComputedStyle(d).fontSize),family:getComputedStyle(d).fontFamily,spacing:getComputedStyle(d).letterSpacing,radius:getComputedStyle(el).borderRadius}});
assert(Math.abs(dict.font-(device==='mac'?19.2:16))<.1);assert(dict.family.includes('PMingLiU'));assert.equal(dict.radius,'22px');assert(dict.x>=0&&dict.y>=0&&dict.x+dict.w<=w+1&&dict.y+dict.h<=h+1);if(device==='iphone')assert(Math.abs(dict.y+dict.h/2-h/2)<2,'phone preview not centered '+JSON.stringify(dict));
await p.locator('#termPreviewClose').click();await p.waitForTimeout(250);
await p.locator('#menuBtn').click();assert(await p.locator('#detailedTourBtn').isVisible());await p.locator('#tourBtn').click();await p.waitForSelector('#tour');await p.waitForTimeout(300);assert.equal(await p.locator('#tour .dots i').count(),6);await p.locator('#tour .sk').click();await p.waitForTimeout(300);await p.evaluate(()=>{__r.showSettingsPage('root');__r.openMenu()});await p.waitForTimeout(250);await p.locator('#detailedTourBtn').click();await p.waitForSelector('#tour');await p.waitForTimeout(300);assert(await p.locator('#tour .dots i').count()>=6);assert.equal(await p.locator('#tour h4').textContent(),'閱讀導覽');await p.locator('#tour .sk').click();await p.waitForTimeout(300);
let layout=await p.evaluate(()=>document.documentElement.dataset.layout);assert.equal(layout,device);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow');
let centered=await p.locator('#readerVolumeTitle').evaluate(el=>{let r=el.getBoundingClientRect(),bar=document.querySelector('.zbar').getBoundingClientRect();return Math.abs(r.x+r.width/2-bar.x-bar.width/2)});assert(centered<1.1,'caption off center '+centered);
// Real volume-heading click uses shared navigation, then all panes match.
await p.evaluate(()=>{__r.goJuan(67);if(document.documentElement.dataset.singlePane==='true')__r.selectReaderPane('catalog',false)});await p.waitForTimeout(1600);if(device==='ipad'&&w>h){await p.locator('#railOpen').click();await p.waitForTimeout(300);}await p.locator('#rinner .rsec[data-j="67"] .rhead').click();await p.waitForTimeout(1700);let sync=await p.evaluate(()=>({j:__r.S.juan,r:__r.S.railJuan,title:document.getElementById('readerVolumeTitle').textContent,p:document.getElementById('pJuan').textContent}));assert.equal(sync.j,67);assert.equal(sync.r,67);assert(sync.title.includes('六十七'));assert(sync.p.includes('六十七'),'chart wrong volume '+sync.p);
await p.evaluate(()=>{let sc=document.getElementById('rscroll');sc.dispatchEvent(new WheelEvent('wheel',{deltaY:80,bubbles:true}));sc.scrollLeft=Math.min(55,sc.scrollWidth-sc.clientWidth);sc._testX=sc.scrollLeft;sc.scrollTop+=90;});await p.waitForTimeout(600);assert(await p.evaluate(()=>Math.abs(document.getElementById('rscroll').scrollLeft-document.getElementById('rscroll')._testX)<1),'catalog panned itself');await p.evaluate(()=>{__r.selectReaderPane('read',false);__r.showSettingsPage('root');__r.openMenu()});await p.waitForTimeout(250);if(device==='mac'){await p.locator('#ftBtn').hover();await p.waitForTimeout(200);await p.locator('#chartTitleColor').hover();await p.mouse.move(w/2,h-10);await p.waitForTimeout(450);assert(await p.locator('#chartTitleColor').isVisible(),'hover flyout collapsed');}else{await p.locator('#ftBtn').click();await p.waitForTimeout(200);}
let visible=await p.locator('#chartTitleColor').isVisible();assert.equal(visible,device==='mac');
if(device==='mac'){
assert(await p.locator('#railPin').isHidden(),'desktop pin visible');assert(await p.evaluate(()=>getComputedStyle(document.querySelector('.rail .books-tools')).backgroundColor===getComputedStyle(document.querySelector('.rail')).backgroundColor),'rail tools white');let inset=await p.evaluate(()=>{let r=document.querySelector('.reader-actions').getBoundingClientRect(),m=document.getElementById('main').getBoundingClientRect(),t=document.querySelector('.zbar>.books-tools').getBoundingClientRect();return {l:r.left-m.left,r:m.right-t.right}});assert(inset.l<=12&&inset.r<=12,'tools not at corners '+JSON.stringify(inset));assert(await p.locator('.reader-actions').evaluate(el=>el.getBoundingClientRect().top>=0),'tools clipped');if(edition==='zang')assert.equal(await p.locator('#labBadge').evaluate(el=>getComputedStyle(el).lineHeight),'12px');let header=await p.locator('#panel>.pbar').evaluate(el=>({pos:getComputedStyle(el).position,h:el.getBoundingClientRect().height}));assert.equal(header.pos,'absolute');assert(header.h<=36.1,'header gap remains');
await p.locator('#chartTitleColor').evaluate(el=>{el.value='#778899';el.dispatchEvent(new Event('input',{bubbles:true}))});let color=await p.locator('.kh .lb').first().evaluate(el=>getComputedStyle(el).color);assert.equal(color,'rgb(119, 136, 153)');assert.notEqual(await p.locator('.kn').first().evaluate(el=>getComputedStyle(el).color),color);assert.equal(await p.evaluate(()=>localStorage.getItem('hk-kepan-label-color-v177')),'#778899');await p.reload();await p.waitForSelector('.txt');assert.equal(await p.locator('.kh .lb').first().evaluate(el=>getComputedStyle(el).color),'rgb(119, 136, 153)');
await p.evaluate(()=>{__r.showSettingsPage('ft');__r.openMenu()});await p.locator('#chartColorReset').click();assert.equal(await p.evaluate(()=>document.documentElement.dataset.customKepanColor),undefined);
await p.locator('#fsReset').click();assert.equal(await p.locator('#fsReset small').isVisible(),false);
}
await p.evaluate(()=>{__r.showSettingsPage('root');__r.openMenu()});await p.waitForTimeout(200);for(let id of ['editionBtn','contentBtn','ftBtn','dlBtn','aboutBtn']){await p.locator('#'+id).click();await p.waitForTimeout(120);assert.notEqual(await p.locator('.settings-panel').getAttribute('data-settings-page'),'root');await p.locator('#settingsBack').click();}
await p.keyboard.press('Escape');await p.waitForTimeout(300);
await p.evaluate(()=>{__r.goJuan(67);__r.selectReaderPane('chart',false)});await p.waitForTimeout(400);let currentChartTitle=await p.locator('#pJuan').textContent();await p.locator('#chartTop').click();await p.waitForTimeout(700);assert.equal(await p.locator('#pJuan').textContent(),currentChartTitle,'single top keeps current volume');await p.locator('#chartTop').dblclick();await p.waitForTimeout(700);assert((await p.locator('#pJuan').textContent()).includes('卷第一'),'double tap first volume');
let chartPage=edition==='hk'?998:95;
await p.evaluate(pg=>{__r.selectReaderPane('chart',false);__r.panelPage(pg);__r.Z.p=1;__r.applyZoom()},chartPage);await p.waitForTimeout(400);
async function chartFits(){let d=await p.evaluate(pg=>{let sh=document.getElementById('pp'+pg),page=sh.querySelector('.page'),pr=page.getBoundingClientRect(),bad=[],ids=[...page.querySelectorAll('[data-id]')].map(e=>e.dataset.id);for(let el of page.querySelectorAll('.nd,svg.ln line')){let rs=[el.getBoundingClientRect()];if(el.classList.contains('nd')){let r=document.createRange();r.selectNodeContents(el);rs.push(r.getBoundingClientRect())}for(let r of rs)if(r.left<pr.left-.7||r.right>pr.right+.7||r.top<pr.top-.7||r.bottom>pr.bottom+.7)bad.push(el.dataset.id||'line')}return {bad,ids}},chartPage);assert.deepEqual(d.bad,[],'paper clipping');return d.ids}
let ids=await chartFits();for(let zoom of [1.5,2]){await p.evaluate(zoom=>{__r.Z.p=zoom;__r.applyZoom()},zoom);await p.waitForTimeout(80);await chartFits();let reach=await p.evaluate(()=>{let v=document.getElementById('pview');v.scrollLeft=0;let sh=[...v.querySelectorAll('.ksheet')].find(e=>e.firstChild&&e.dataset.p===String(document.getElementById('pageCurrent').textContent)),r=sh.getBoundingClientRect(),vr=v.getBoundingClientRect(),left=r.left-vr.left;v.scrollLeft=v.scrollWidth;return {left,right:sh.getBoundingClientRect().right-vr.right}});assert(reach.left>=-1&&reach.right<=1,'zoom content unreachable '+JSON.stringify(reach));}
// A forced out-of-paper subtree must fit without losing any title or connector.
await p.evaluate(pg=>{let page=document.getElementById('pp'+pg).querySelector('.page'),group=page.querySelector('.shift')||page.querySelector('.nd');group.style.transform+=' translate(-160px,0) scale(1.35)';delete page.dataset.boundsEpoch;__r.fitChartBounds(page)},chartPage);assert.deepEqual(await chartFits(),ids,'guard loses titles');
await p.evaluate(pg=>{let sh=document.getElementById('pp'+pg);__r.fillPage(sh,pg);let ff=new FontFace('TWKai','local("Arial")');document.fonts.dispatchEvent(new FontFaceSetLoadEvent('loadingdone',{fontfaces:[ff]}))},chartPage);await p.waitForTimeout(450);assert.deepEqual(await chartFits(),ids,'font refresh loses titles');
await p.evaluate(()=>{__r.Z.p=1;__r.applyZoom();__r.selectReaderPane('read',false)});
if(device==='mac'){await p.locator('#swapPanes').click();assert(await p.locator('#wrap').evaluate(el=>el.classList.contains('panes-swapped')));await p.locator('#swapPanes').click();await p.locator('#searchButton').click();assert(await p.locator('#q').isVisible());await p.keyboard.press('Escape');await p.locator('#panel .books-tools .book-size-button').click();assert(await p.locator('#bookSize').isVisible());await p.locator('#bookSize [data-size="1"]').click();assert.equal(await p.locator('#bookPercent').textContent(),'110%');await p.keyboard.press('Escape');await p.waitForTimeout(300);}if(device==='mac'&&w===1440){await p.screenshot({path:path.join(root,'tools/desktop179.png')});}
results.push({name,edition,centered,volume:sync,desktopColor:visible,passed:true});console.log('PASS',name,edition);await c.close();
}let cases=profiles.flatMap(x=>['zang','hk'].map(ed=>[...x,ed])),next=0;await Promise.all([0,1].map(async()=>{while(next<cases.length){let task=cases[next++];await check(task)}}));assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'tools/regression179-results.json'),JSON.stringify({results,errors},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1)});
