const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');let errors=[],results=[];
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/yogacara\//,'')||'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf8':f.endsWith('.js')?'application/javascript':'application/octet-stream');let s=fs.readFileSync(f);if(f.endsWith('index.html'))s=s.toString().replace('\n})();','\nwindow.__r={S,goJuan,selectReaderPane,showSettingsPage,openMenu,setLabel,focusNode,spy,railFocus,applyChartTitleColor,get N(){return N}};\n})();');res.end(s);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser=await chromium.launch({executablePath:'/tmp/chrome176/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});try{
for(let [name,w,h,device] of [['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']])for(let edition of ['zang','hk']){
let c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});await c.addInitScript(({edition,device})=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154',edition);localStorage.setItem('hk-device-layout-v146',device);Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5});},{edition,device});let p=await c.newPage();p.on('pageerror',e=>{errors.push(name+':'+e.message);console.error('PAGE',e.message)});await p.route('**/sw.js',r=>r.fulfill({status:404,body:''}));await p.goto(`http://127.0.0.1:${server.address().port}/yogacara/`);await p.waitForSelector('.txt');await p.waitForTimeout(900);
let layout=await p.evaluate(()=>document.documentElement.dataset.layout);assert.equal(layout,device);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow');
let centered=await p.locator('#readerVolumeTitle').evaluate(el=>{let r=el.getBoundingClientRect(),bar=document.querySelector('.zbar').getBoundingClientRect();return Math.abs(r.x+r.width/2-bar.x-bar.width/2)});assert(centered<1.1,'caption off center '+centered);
// Real volume-heading click uses shared navigation, then all panes match.
await p.evaluate(()=>{__r.goJuan(67);if(document.documentElement.dataset.singlePane==='true')__r.selectReaderPane('catalog',false)});await p.waitForTimeout(1600);if(device==='ipad'&&w>h){await p.locator('#railOpen').click();await p.waitForTimeout(300);}await p.locator('#rinner .rsec[data-j="67"] .rhead').click();await p.waitForTimeout(1700);let sync=await p.evaluate(()=>({j:__r.S.juan,r:__r.S.railJuan,title:document.getElementById('readerVolumeTitle').textContent,p:document.getElementById('pJuan').textContent}));assert.equal(sync.j,67);assert.equal(sync.r,67);assert(sync.title.includes('六十七'));assert(sync.p.includes('六十七'),'chart wrong volume '+sync.p);
await p.evaluate(()=>{__r.selectReaderPane('read',false);__r.showSettingsPage('root');__r.openMenu()});await p.waitForTimeout(250);await p.locator('#ftBtn').click();await p.waitForTimeout(200);
let visible=await p.locator('#chartTitleColor').isVisible();assert.equal(visible,device==='mac');
if(device==='mac'){
assert(await p.locator('#railPin').isHidden(),'desktop pin visible');let header=await p.locator('#panel>.pbar').evaluate(el=>({pos:getComputedStyle(el).position,h:el.getBoundingClientRect().height}));assert.equal(header.pos,'absolute');assert(header.h<=36.1,'header gap remains');
await p.locator('#chartTitleColor').evaluate(el=>{el.value='#778899';el.dispatchEvent(new Event('input',{bubbles:true}))});let color=await p.locator('.kn').first().evaluate(el=>getComputedStyle(el).color);assert.equal(color,'rgb(119, 136, 153)');assert.equal(await p.evaluate(()=>localStorage.getItem('hk-chart-title-color-v176')),'#778899');await p.reload();await p.waitForSelector('.txt');assert.equal(await p.locator('.kn').first().evaluate(el=>getComputedStyle(el).color),'rgb(119, 136, 153)');
await p.evaluate(()=>{__r.showSettingsPage('ft');__r.openMenu()});await p.locator('#chartColorReset').click();assert.equal(await p.evaluate(()=>document.documentElement.dataset.customKepanColor),undefined);
await p.locator('#fsReset').click();assert.equal(await p.locator('#fsReset small').isVisible(),false);
}
await p.evaluate(()=>{__r.showSettingsPage('root');__r.openMenu()});await p.waitForTimeout(200);for(let id of ['editionBtn','contentBtn','ftBtn','dlBtn','aboutBtn']){await p.locator('#'+id).click();await p.waitForTimeout(120);assert.notEqual(await p.locator('.settings-panel').getAttribute('data-settings-page'),'root');await p.locator('#settingsBack').click();}
await p.keyboard.press('Escape');await p.waitForTimeout(300);if(device==='mac'){await p.locator('#swapPanes').click();assert(await p.locator('#wrap').evaluate(el=>el.classList.contains('panes-swapped')));await p.locator('#swapPanes').click();await p.locator('#searchButton').click();assert(await p.locator('#q').isVisible());await p.keyboard.press('Escape');await p.locator('#panel .books-tools .book-size-button').click();assert(await p.locator('#bookSize').isVisible());await p.locator('#bookSize [data-size="1"]').click();assert.equal(await p.locator('#bookPercent').textContent(),'110%');await p.keyboard.press('Escape');}if(device==='mac'&&w===1440){await p.screenshot({path:path.join(root,'tools/desktop176.png')});}
results.push({name,edition,centered,volume:sync,desktopColor:visible,passed:true});console.log('PASS',name,edition);await c.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'tools/regression176-results.json'),JSON.stringify({results,errors},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1)});
