const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),errors=[],results=[];
const server=http.createServer((req,res)=>{let file=path.join(root,req.url.split('?')[0].replace(/^\//,'')||'index.html');if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':'application/octet-stream');if(file.endsWith('index.html')){let s=fs.readFileSync(file,'utf8').replace('\n})();\n</script>','\nwindow.__r={state:()=>({S,screen:ReaderUI.screen,LABEL,EDITION,zoom:Z.p,pending:pendingPanel}),N:()=>N,focusNode,openText,renderRail,panelPage,setLabel,goJuan,chartAnchor,selectReaderPane,saveReadingPosition};\n})();\n</script>');res.end(s);}else fs.createReadStream(file).pipe(res);});
let browser;
const sizes=[['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad-portrait',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']];
async function fits(p){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document overflow');}
async function choose(p,j){await p.evaluate(j=>__r.goJuan(j),j);await p.waitForSelector('#volume-'+j);await p.waitForTimeout(220);let st=await p.evaluate(()=>__r.state());assert.equal(st.S.juan,j);assert.equal(st.S.railJuan,j);assert.equal(await p.locator('#readerVolumeTitle').textContent(),'卷第'+await p.evaluate(j=>{const c='〇一二三四五六七八九';return j<10?c[j]:j<20?'十'+(j%10?c[j%10]:''):j<100?c[Math.floor(j/10)]+'十'+(j%10?c[j%10]:''):'一百'},j));}
async function pinch(p){let session=await p.context().newCDPSession(p),a=await p.evaluate(()=>{let a=__r.chartAnchor(),pv=document.getElementById('pview'),r=pv.getBoundingClientRect(),rect=a.page.getBoundingClientRect();return {page:a.page.id,x:a.x,y:a.y,vx:a.vx,vy:a.vy,cx:r.left+a.vx,cy:r.top+a.vy,zoom:__r.state().zoom};});let space=Math.min(35,a.cx-5,p.viewportSize().width-a.cx-5);let points=(scale)=>[{x:a.cx-space*scale,y:a.cy,id:1},{x:a.cx+space*scale,y:a.cy,id:2}];await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(1)});await p.waitForTimeout(600);await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(1.5)});await p.waitForTimeout(90);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(350);let after=await p.evaluate(a=>{let r=document.getElementById(a.page).getBoundingClientRect(),pv=document.getElementById('pview').getBoundingClientRect();return {dx:r.left+a.x*r.width-pv.left-a.vx,dy:r.top+a.y*r.height-pv.top-a.vy,state:__r.state(),transform:document.getElementById('pzoom').style.transform};},a);assert.equal(after.state.zoom,Math.round(a.zoom*1.5*10)/10);assert.equal(after.transform,'');assert(Math.abs(after.dy)<8,'pinch changed vertical point '+after.dy);assert(Math.abs(after.dx)<8,'pinch changed horizontal point '+after.dx);return after;}
(async()=>{await new Promise(r=>server.listen(8783,'127.0.0.1',r));browser=await chromium.launch({executablePath:'/tmp/headless161/chrome-linux/headless_shell',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const [name,w,h,device]of sizes)for(const ed of ['hk','zang']){
 const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});await c.addInitScript(({device,ed})=>{try{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154',ed);if(device==='mac')localStorage.setItem('hk-device-layout-v146','mac');Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5});}catch(e){}},{device,ed});await c.route('**/sw.js',r=>r.fulfill({status:404}));let p=await c.newPage();p.on('pageerror',e=>errors.push(name+' '+ed+' '+e.message));await p.route('https://deerpark.app/**',r=>r.fulfill({contentType:'text/html',body:'<p>Test</p>'}));await p.goto('http://127.0.0.1:8783/#j67');await p.waitForSelector('#volume-67');await fits(p);const single=await p.evaluate(()=>document.documentElement.dataset.singlePane==='true');
 for(let k=0;k<6;k++){if(single)await p.locator('[data-screen=catalog]').click();let a=p.locator('.rol a').nth(k),id=await a.getAttribute('data-n');if(device==='iphone')await a.tap();else await a.click();await p.waitForTimeout(k<2?1900:350);let st=await p.evaluate(()=>__r.state());assert.equal(st.S.juan,67,name+' '+ed+' heading '+k+' changed volume');assert.equal(st.S.railJuan,67);assert.equal(st.S.cur,+id);assert.equal(await p.evaluate(()=>location.hash),'#j67');}
 for(let j of [56,1,100,67]){await choose(p,j);if(single){await p.locator('[data-screen=chart]').click();await p.waitForTimeout(200);let a=await p.evaluate(()=>{let state=__r.state(),el=document.getElementById('pp'+state.S.ppage),r=el.getBoundingClientRect(),pv=document.getElementById('pview').getBoundingClientRect();return {state,top:r.top,bottom:r.bottom,pv};});assert(a.bottom>a.pv.top&&a.top<a.pv.bottom,'selected volume chart hidden '+j);await p.locator('[data-screen=read]').click();}await fits(p);}
 if(device!=='mac'){if(single)await p.locator('[data-screen=chart]').click();await p.evaluate(()=>{let pv=document.getElementById('pview');pv.scrollTop+=Math.min(180,pv.clientHeight/2)});await p.waitForTimeout(800);await pinch(p);if(single)await p.locator('[data-screen=read]').click();}
 await p.locator('#menuBtn').click();await p.locator('#labelBtn').click();await p.locator('[data-label=zj]').click();await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>__r.state().LABEL),'zj');assert(/\d/.test(await p.locator('#rinner .lb').first().textContent()),'chapter label unavailable '+ed);assert.equal((await p.evaluate(()=>__r.state())).S.juan,67);await p.locator('[data-label=gz]').click();await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>__r.state().LABEL),'gz');await p.keyboard.press('Escape');await p.waitForTimeout(230);await fits(p);
 if(device!=='mac'){
 await p.evaluate(()=>{let el=Array.from(document.querySelectorAll('#article .txt p')).find(e=>/有情|無明|菩薩|法性|瑜伽/.test(e.textContent));if(!el)throw Error('No dictionary term');el.scrollIntoView({block:'center'});let walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),n;while(n=walker.nextNode()){let m=/有情|無明|菩薩|法性|瑜伽/.exec(n.textContent);if(m){let r=document.createRange();r.setStart(n,m.index);r.setEnd(n,m.index+m[0].length);getSelection().removeAllRanges();getSelection().addRange(r);break}}});await p.waitForTimeout(800);await p.locator('.dict-chip').click();await p.waitForTimeout(300);let d=await p.locator('#termPreview').boundingBox();assert(d.x>=0&&d.x+d.width<=w+1&&d.y>=0&&d.y+d.height<=h+1,'dictionary overflow '+name);await p.locator('#termPreviewClose').click();await p.waitForTimeout(230);
 }
 await p.evaluate(()=>{getSelection().removeAllRanges();scrollTo(0,600);__r.saveReadingPosition()});await p.waitForTimeout(100);const savedPosition=await p.evaluate(()=>{let k=__r.state().EDITION==='zang'?'hk-reading-position-zang-v154':'hk-reading-position-v149';return JSON.parse(localStorage.getItem(k))});const savedY=await p.evaluate(()=>scrollY);await p.reload();await p.waitForSelector('#volume-67');await p.waitForTimeout(1800);let restoredOffset=await p.locator('[id=\"'+savedPosition.id+'\"]').evaluate(e=>e.getBoundingClientRect().top);assert(Math.abs(restoredOffset-savedPosition.offset)<6,'reload changed reading anchor '+name+' '+ed+' before='+savedPosition.offset+' after='+restoredOffset);await fits(p);
 if(device==='iphone')assert.equal(await p.locator('.reading-volume').count(),1,'phone scrollbar spans multiple volumes');
 await p.screenshot({path:path.join(__dirname,'verified163-'+name+'-'+ed+'.png')});results.push({name,ed,frontHeadings67:true,volumeSync:true,labelSwitch:true,pinch:device!=='mac',bottomDictionary:device!=='mac',reloadPosition:true,fits:true});console.log('PASS',name,ed);await c.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'regression163-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close();})().catch(async e=>{console.error(e.stack);if(browser)await browser.close();server.close();process.exitCode=1});
