const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),errors=[],results=[];
const server=http.createServer((req,res)=>{let file=path.join(root,req.url.split('?')[0].replace(/^\//,'')||'index.html');if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':'application/octet-stream');if(file.endsWith('index.html')){let s=fs.readFileSync(file,'utf8').replace('\n})();\n</script>','\nwindow.__r={state:()=>({S,screen:ReaderUI.screen,LABEL,EDITION,zoom:Z.p,pending:pendingPanel}),N:()=>N,focusNode,openText,renderRail,panelPage,setLabel,goJuan,chartAnchor,selectReaderPane,saveReadingPosition,localNode};\n})();\n</script>');res.end(s);}else fs.createReadStream(file).pipe(res);});
let browser;
const sizes=[['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad-portrait',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']];
async function fits(p){assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document overflow');}
async function choose(p,j){await p.evaluate(j=>__r.goJuan(j),j);await p.waitForSelector('#volume-'+j);await p.waitForTimeout(220);let st=await p.evaluate(()=>__r.state());assert.equal(st.S.juan,j);assert.equal(st.S.railJuan,j);assert.equal(await p.locator('#readerVolumeTitle').textContent(),'卷第'+await p.evaluate(j=>{const c='〇一二三四五六七八九';return j<10?c[j]:j<20?'十'+(j%10?c[j%10]:''):j<100?c[Math.floor(j/10)]+'十'+(j%10?c[j%10]:''):'一百'},j));}
async function pinch(p){let session=await p.context().newCDPSession(p),a=await p.evaluate(()=>{let a=__r.chartAnchor(),pv=document.getElementById('pview'),r=pv.getBoundingClientRect(),rect=a.page.getBoundingClientRect();return {page:a.page.id,x:a.x,y:a.y,vx:a.vx,vy:a.vy,cx:r.left+a.vx,cy:r.top+a.vy,zoom:__r.state().zoom};});let space=Math.min(35,a.cx-5,p.viewportSize().width-a.cx-5);let points=(scale)=>[{x:a.cx-space*scale,y:a.cy,id:1},{x:a.cx+space*scale,y:a.cy,id:2}];await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(1)});await p.waitForTimeout(600);await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(1.5)});await p.waitForTimeout(90);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(350);let after=await p.evaluate(a=>{let r=document.getElementById(a.page).getBoundingClientRect(),pv=document.getElementById('pview').getBoundingClientRect();return {dx:r.left+a.x*r.width-pv.left-a.vx,dy:r.top+a.y*r.height-pv.top-a.vy,state:__r.state(),transform:document.getElementById('pzoom').style.transform};},a);assert.equal(after.state.zoom,Math.round(a.zoom*1.5*10)/10);assert.equal(after.transform,'');assert(Math.abs(after.dy)<8,'pinch changed vertical point '+after.dy);assert(Math.abs(after.dx)<8,'pinch changed horizontal point '+after.dx);return after;}

(async()=>{await new Promise(r=>server.listen(8793,'127.0.0.1',r));browser=await chromium.launch({executablePath:'/tmp/headless161/chrome-linux/headless_shell',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const [name,w,h,device]of sizes)for(const ed of ['hk','zang']){
 const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});await c.addInitScript(({device,ed})=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154',ed);if(device==='mac')localStorage.setItem('hk-device-layout-v146','mac');Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5});},{device,ed});await c.route('**/sw.js',r=>r.fulfill({status:404}));let p=await c.newPage();p.on('pageerror',e=>errors.push(name+' '+ed+' '+e.message));await p.goto('http://127.0.0.1:8793/#j67');await p.waitForSelector('#volume-67');await p.waitForTimeout(1800);
 const single=await p.evaluate(()=>document.documentElement.dataset.singlePane==='true');
 async function pane(which){if(single){await p.locator('[data-screen='+which+']').click();await p.waitForTimeout(160);}}
 async function linked(i){let actual=await p.evaluate(i=>{let st=__r.state(),k=__r.localNode(i,st.S.juan),kn=document.querySelector('[id="k'+k+'"]'),a=document.querySelector('.rol a[data-n="'+i+'"]'),nd=document.querySelector('#pp'+st.S.ppage+' .nd[data-id="'+i+'"]');return {juan:st.S.juan,cur:st.S.cur,body:!!kn?.classList.contains('on'),rail:!!a?.classList.contains('cur'),chart:!!nd?.classList.contains('on'),colors:[kn,a,nd].map(e=>e?getComputedStyle(e).backgroundColor:null)};},i);assert.equal(actual.cur,i);assert.equal(actual.juan,67);assert(actual.body&&actual.rail&&actual.chart,'highlight '+name+' '+ed+' '+JSON.stringify(actual));assert(actual.colors.every(x=>x===actual.colors[0]),'different colors '+JSON.stringify(actual));}
 async function position(which,i){await pane(which);let v=await p.evaluate(({which,i})=>{let st=__r.state(),k=__r.localNode(i,st.S.juan),el=which==='read'?document.querySelector('[id="k'+k+'"]'):document.querySelector('#pp'+st.S.ppage+' .nd[data-id="'+i+'"]'),r=el.getBoundingClientRect();if(which==='chart'){let pv=document.getElementById('pview'),v=pv.getBoundingClientRect();return {fraction:(r.top-v.top)/pv.clientHeight,edge:pv.scrollTop<1};}let bar=document.querySelector('.zbar').getBoundingClientRect().bottom,bottom=st.screen==='read'&&document.documentElement.dataset.layout==='iphone'?document.querySelector('.device-tabs').getBoundingClientRect().top:innerHeight;return {fraction:(r.top-bar)/(bottom-bar),edge:scrollY<1};},{which,i});assert(v.edge||Math.abs(v.fraction-(which==='chart'?1/3:.30))<.055,'position '+name+' '+which+' '+JSON.stringify(v));}
 let ids=await p.locator('#volume-67 .kn').evaluateAll(es=>es.slice(1,5).map(e=>+e.dataset.kn));assert(ids.length>=3);
 for(const [n,source]of ['catalog','read','chart'].entries()){
  let i=ids[n];await p.evaluate(i=>__r.focusNode(i,'rail',null,67),i);await p.waitForTimeout(170);await pane(source);
  let target=source==='catalog'?p.locator('.rol a[data-n="'+i+'"]'):source==='read'?p.locator('#volume-67 .kn[data-kn="'+i+'"]'):p.locator('#pp'+(await p.evaluate(()=>__r.state().S.ppage))+' .nd[data-id="'+i+'"]').first();
  if(device==='iphone')await target.tap();else await target.click();await p.waitForTimeout(450);
  await pane('chart');await linked(i);await position('chart',i);await position('read',i);await fits(p);
 }
 // Passive body scroll selects the heading crossed at the reading line, without recentering body.
 await pane('read');let i=ids[3];await p.waitForTimeout(1900);let before=await p.evaluate(i=>{let el=document.querySelector('#volume-67 .kn[data-kn="'+i+'"]');el.dispatchEvent(new WheelEvent('wheel',{deltaY:300,bubbles:true}));scrollBy(0,el.getBoundingClientRect().top-((parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--hh'))||0)+55));return scrollY;},i);await p.waitForTimeout(250);before=await p.evaluate(i=>{let el=document.querySelector('#volume-67 .kn[data-kn="'+i+'"]');scrollBy(0,el.getBoundingClientRect().top-55);return scrollY;},i);await p.waitForTimeout(180);let st=await p.evaluate(()=>__r.state());assert.equal(st.S.cur,i,'scroll heading '+name+' '+ed+' actual='+st.S.cur+' expected='+i);assert(Math.abs(await p.evaluate(()=>scrollY)-before)<3,'spy moved body');await pane('chart');await linked(i);await position('chart',i);await p.screenshot({path:path.join(__dirname,'chart163-'+name+'-'+ed+'.png')});results.push({name,ed,clickAllThree:true,sameYellow:true,upperMiddle:true,scrollHighlight:true});console.log('PASS sync',name,ed);await c.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'sync163-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close();})().catch(async e=>{console.error(e.stack);if(browser)await browser.close();server.close();process.exitCode=1});
