const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert'),{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');let browser;const results=[],errors=[];
const server=http.createServer((req,res)=>{let f=path.join(root,req.url.split('?')[0].replace(/^\//,'')||'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html;charset=utf-8':'application/javascript');if(f.endsWith('index.html'))res.end(fs.readFileSync(f,'utf8').replace('\n})();\n</script>','\nwindow.__r={state:()=>({S,tracking:readerTracking,screen:ReaderUI.screen,Z}),focusNode,goJuan,zoomBy,setFont,showSettingsPage};\n})();\n</script>'));else fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(8795,'127.0.0.1',r));browser=await chromium.launch({executablePath:'/tmp/headless161/chrome-linux/headless_shell',args:['--no-sandbox','--disable-dev-shm-usage']});
for(const [name,w,h,device]of [['phone',390,844,'iphone'],['phone-landscape',844,390,'iphone'],['ipad-portrait',768,1024,'ipad'],['ipad-landscape',1024,768,'ipad'],['desktop-narrow',900,700,'mac'],['desktop',1440,900,'mac']]){
 const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:device!=='mac',userAgent:device==='iphone'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)':'Mozilla/5.0 (Macintosh; Intel Mac OS X)'});await c.addInitScript(device=>{localStorage.setItem('hk-tour','7');localStorage.setItem('hk-edition-v154','zang');if(device==='mac')localStorage.setItem('hk-device-layout-v146','mac');Object.defineProperty(navigator,'maxTouchPoints',{get:()=>device==='mac'?0:5});},device);await c.route('**/sw.js',r=>r.fulfill({status:404}));let p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8795/#j67');await p.waitForSelector('#volume-67');await p.waitForTimeout(500);
 if(device==='iphone'){
  assert.equal(await p.locator('.zbar .book-size-button:visible').count(),0);assert.equal(await p.locator('.zbar #searchButton:visible').count(),1);
  let center=await p.locator('#readerVolumeTitle').boundingBox(),bar=await p.locator('.zbar').boundingBox();assert(Math.abs(center.x+center.width/2-bar.x-bar.width/2)<2,'title not centered');
  await p.locator('.phone-juan-button').tap();assert(await p.locator('#juans').isVisible());assert.equal(await p.locator('#juans a').count(),100);let r=await p.locator('#juans').boundingBox();assert(r.x>=0&&r.x+r.width<=w+1&&r.y+r.height<=h+1,'juan popup overflow');await p.locator('#juans a[data-j="56"]').tap();await p.waitForSelector('#volume-56');assert.equal((await p.evaluate(()=>__r.state())).S.juan,56);await p.waitForTimeout(250);assert(!(await p.locator('#juans').isVisible()));
  await p.evaluate(()=>{for(let i=0;i<30;i++)__r.zoomBy('p',-1)});assert.equal((await p.evaluate(()=>__r.state())).Z.p,1);await p.evaluate(()=>{for(let i=0;i<30;i++)__r.zoomBy('p',1)});assert.equal((await p.evaluate(()=>__r.state())).Z.p,2);await p.evaluate(()=>__r.setFont(.5,null,true));assert.equal((await p.evaluate(()=>__r.state())).Z.p,1);await p.evaluate(()=>__r.setFont(1,null,true));
  await p.locator('[data-screen=chart]').tap();await p.waitForTimeout(250);const touch=await c.newCDPSession(p);
  async function pinchBound(ratio,want){let q=await p.locator('#pview').boundingBox(),cx=q.x+q.width/2,cy=q.y+q.height/2,points=scale=>[{id:1,x:cx-30*scale,y:cy},{id:2,x:cx+30*scale,y:cy}];await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(1)});await p.waitForTimeout(120);await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(ratio)});await p.waitForTimeout(60);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(300);assert.equal((await p.evaluate(()=>__r.state())).Z.p,want,'pinch clamp');assert.equal(await p.locator('#pzoom').evaluate(e=>e.style.transform),'');}
  await pinchBound(4,2);await pinchBound(.1,1);await p.locator('[data-screen=read]').tap();
 }else{assert.equal(await p.locator('.rail .book-size-button,.panel .book-size-button').count(),0);assert.equal(await p.locator('.zbar .book-size-button:visible').count(),1);}
 await p.locator('#menuBtn').click();assert.deepEqual(await p.locator('.settings-section:visible').allTextContents(),['閱讀','顯示','其他']);assert.equal(await p.locator('[data-settings-group="0"]>.mi,[data-settings-group="0"].mi').count(),4);assert.equal(await p.locator('[data-settings-group="1"]>.mi,[data-settings-group="1"]>.learning-settings>summary.mi').count(),2);assert.equal(await p.locator('[data-settings-group="2"]>.mi').count(),2);assert.equal(await p.locator('#editionCur').textContent(),'藏版');let corner=await p.locator('#tourBtn').evaluate(e=>({radius:getComputedStyle(e).borderBottomLeftRadius,background:getComputedStyle(e).backgroundImage}));assert.equal(corner.radius,'14px');assert.equal(corner.background,'none');
 for(const [id,page]of [['editionBtn','edition'],['labelBtn','label'],['contentBtn','content'],['layoutBtn','layout'],['ftBtn','ft'],['dlBtn','dl'],['aboutBtn','about']]){
  if(id==='layoutBtn')await p.locator('.learning-settings summary').click();else await p.locator('#'+id).click();assert.equal(await p.locator('.settings-panel').getAttribute('data-settings-page'),page,id+' entry failed');let b=await p.locator('.settings-panel').boundingBox();assert(b.x>=-1&&b.x+b.width<=w+1&&b.y+b.height<=h+1,'menu overflow '+name+' '+page);
  if(page==='ft'){assert.equal(await p.locator('.font-pane-row').count(),3);let btn=p.locator('.font-pane-row .book-size-button').last();await btn.click();assert(await p.locator('#bookSize').isVisible());assert(await p.locator('#bookPercent').textContent());await p.locator('#bookSize [data-size="1"]').click();await p.locator('#settingsBack').click();await p.waitForTimeout(230);continue;}
  await p.locator('#settingsBack').click();assert.equal(await p.locator('.settings-panel').getAttribute('data-settings-page'),'root');
 }
 await p.screenshot({path:path.join(__dirname,'menu163-'+name+'.png')});await p.locator('#tourBtn').click();assert(await p.locator('#tour').count()>0,'tour entry failed');await p.locator('#tour .sk').click();await p.waitForTimeout(240);await p.keyboard.press('Escape');
 if(device==='mac'){
  await p.evaluate(()=>__r.goJuan(67));await p.waitForTimeout(1800);let ids=await p.locator('#volume-67 .kn').evaluateAll(es=>es.slice(2,5).map(e=>+e.dataset.kn));await p.evaluate(i=>__r.focusNode(i,'text',null,67),ids[0]);await p.waitForTimeout(170);
  await p.evaluate(i=>{let el=document.querySelector('#volume-67 .kn[data-kn="'+i+'"]');el.dispatchEvent(new WheelEvent('wheel',{deltaY:300,bubbles:true}));scrollBy(0,el.getBoundingClientRect().top-55);},ids[1]);await p.waitForTimeout(300);await p.evaluate(i=>{let el=document.querySelector('#volume-67 .kn[data-kn="'+i+'"]');scrollBy(0,el.getBoundingClientRect().top-55);},ids[1]);await p.waitForTimeout(200);assert.equal((await p.evaluate(()=>__r.state())).S.cur,ids[1]);let pos=await p.evaluate(i=>{let pv=document.getElementById('pview'),el=pv.querySelector('.nd[data-id="'+i+'"]');return (el.getBoundingClientRect().top-pv.getBoundingClientRect().top)/pv.clientHeight},ids[1]);assert(Math.abs(pos-1/3)<.03,'same-page chart not following');
  await p.locator('#main').dispatchEvent('pointerdown');assert.equal((await p.evaluate(()=>__r.state())).tracking,false);assert.equal(await p.locator('.kn.on,.rol a.cur,#pzoom .nd.on').count(),0);await p.mouse.wheel(0,150);await p.waitForTimeout(200);assert.equal(await p.locator('.kn.on,.rol a.cur,#pzoom .nd.on').count(),0,'blank click did not stop');await p.evaluate(i=>__r.focusNode(i,'text',null,67),ids[2]);assert((await p.evaluate(()=>__r.state())).tracking);
 }
 results.push({name,groups:true,eightEntries:true,phoneJuan:device==='iphone',phoneZoomBounds:device==='iphone',phonePinchBounds:device==='iphone',desktopTracking:device==='mac',viewportFits:true});console.log('PASS ui',name);await c.close();
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'ui163-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close();})().catch(async e=>{console.error(e.stack);if(browser)await browser.close();server.close();process.exitCode=1});
